name: C/C++ CI

on:
  push:
    branches: [ "master" ]  # Workflow dijalankan saat ada push ke branch master
  pull_request:
    branches: [ "master" ]  # Workflow dijalankan saat ada PR ke branch master

jobs:
  build:
    runs-on: ubuntu-latest  # Menjalankan job di sistem Ubuntu terbaru

    steps:
    # 1. Checkout kode dari repositori
    - uses: actions/checkout@v4

    # 2. Konfigurasi proyek (menggunakan ./configure, biasanya untuk C/C++ proyek)
    - name: configure
      run: ./configure

    # 3. Kompilasi proyek menggunakan make
    - name: make
      run: make

    # 4. Jalankan pengujian otomatis, biasanya digunakan untuk unit tests
    - name: make check
      run: make check

    # 5. Pastikan build siap untuk distribusi
    - name: make distcheck
      run: make distcheck
